# aks-release.yaml

parameters:
  - name: vmImage
    default: 'ubuntu-latest'
    type: string
  - name: poolName
    default: 'Azure Pipelines'
    type: string
  - name: 'location'
    default: 'australiaeast'
    type: string
  - name: azureServiceConnection
    type: string
  - name: subscriptionId
    type: string

stages:
- stage: dev
  condition: succeededOrFailed()
  jobs:
  - deployment: 
    displayName: 'Dev AKS Deployment'
    pool:
      name: ${{parameters.poolName}}
    environment: aks-cicd-demo-dev
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: $(System.ArtifactsDirectory)
            - task: AzurePowerShell@5
              displayName: 'Get subscription Deployment outputs'
              inputs:
                azureSubscription: ${{parameters.azureServiceConnection}}
                azurePowerShellVersion: LatestVersion
                ScriptType: InlineScript
                pwsh: true
                Inline: |
                  $deployment = Get-AzSubscriptionDeployment -Name 'aks-cicd-demo-infra-deployment-dev'
                  Write-Host "##vso[task.setvariable variable=aksSystemSubnetId;]$($deployment.Outputs.aksSystemSubnetId.value)"
                  Write-Host "##vso[task.setvariable variable=aksUserSubnetId;]$($deployment.Outputs.aksUserSubnetId.value)"
                  Write-Host "##vso[task.setvariable variable=azMonitorWorkspaceId;]$($deployment.Outputs.azMonitorWorkspaceId.value)"
                  Write-Host "##vso[task.setvariable variable=workloadResourceGroupName;]$($deployment.Outputs.workloadResourceGroupName.value)"
                  Write-Host "##vso[task.setvariable variable=monitorResourceGroupName;]$($deployment.Outputs.monitorResourceGroupName.value)"
                  Write-Host "##vso[task.setvariable variable=networkResourceGroupName;]$($deployment.Outputs.networkResourceGroupName.value)"
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Validate Templates'
              inputs:
                deploymentScope: Subscription
                azureResourceManagerConnection: ${{parameters.azureServiceConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/aks-main.bicep'
                csmParametersFile: '$(System.ArtifactsDirectory)/parameters/dev/aks.parameters.json'
                overrideParameters: '-location $(location) -resourceGroupName $(workloadResourceGroupName) -aksSystemSubnetId $(aksSystemSubnetId) -aksUserSubnetId $(aksUserSubnetId) -azMonitorWorkspaceId $(azMonitorWorkspaceId)'
                deploymentMode: Validation
                deploymentName: 'aks-cicd-demo-aks-validation-dev'
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Templates'
              inputs:
                deploymentScope: Subscription
                azureResourceManagerConnection: ${{parameters.azureServiceConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/aks-main.bicep'
                csmParametersFile: '$(System.ArtifactsDirectory)/parameters/dev/aks.parameters.json'
                overrideParameters: '-location $(location) -resourceGroupName $(workloadResourceGroupName) -aksSystemSubnetId $(aksSystemSubnetId) -aksUserSubnetId $(aksUserSubnetId) -azMonitorWorkspaceId $(azMonitorWorkspaceId)'
                deploymentMode: Incremental
                deploymentName: 'aks-cicd-demo-aks-deployment-dev'
- stage: test
  condition: succeededOrFailed()
  jobs:
  - deployment: 
    displayName: 'Test AKS Deployment'
    pool:
      name: ${{parameters.poolName}}
    environment: aks-cicd-demo-test
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: $(System.ArtifactsDirectory)
            - task: AzurePowerShell@5
              displayName: 'Get subscription Deployment outputs'
              inputs:
                azureSubscription: ${{parameters.azureServiceConnection}}
                azurePowerShellVersion: LatestVersion
                ScriptType: InlineScript
                pwsh: true
                Inline: |
                  $deployment = Get-AzSubscriptionDeployment -Name 'aks-cicd-demo-infra-deployment-test'
                  Write-Host "##vso[task.setvariable variable=aksSystemSubnetId;]$($deployment.Outputs.aksSystemSubnetId.value)"
                  Write-Host "##vso[task.setvariable variable=aksUserSubnetId;]$($deployment.Outputs.aksUserSubnetId.value)"
                  Write-Host "##vso[task.setvariable variable=azMonitorWorkspaceId;]$($deployment.Outputs.azMonitorWorkspaceId.value)"
                  Write-Host "##vso[task.setvariable variable=workloadResourceGroupName;]$($deployment.Outputs.workloadResourceGroupName.value)"
                  Write-Host "##vso[task.setvariable variable=monitorResourceGroupName;]$($deployment.Outputs.monitorResourceGroupName.value)"
                  Write-Host "##vso[task.setvariable variable=networkResourceGroupName;]$($deployment.Outputs.networkResourceGroupName.value)"
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Validate Templates'
              inputs:
                deploymentScope: Subscription
                azureResourceManagerConnection: ${{parameters.azureServiceConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/aks-main.bicep'
                csmParametersFile: '$(System.ArtifactsDirectory)/parameters/test/aks.parameters.json'
                overrideParameters: '-location $(location) -resourceGroupName $(workloadResourceGroupName) -aksSystemSubnetId $(aksSystemSubnetId) -aksUserSubnetId $(aksUserSubnetId) -azMonitorWorkspaceId $(azMonitorWorkspaceId)'
                deploymentMode: Validation
                deploymentName: 'aks-cicd-demo-aks-validation-test'
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Templates'
              inputs:
                deploymentScope: Subscription
                azureResourceManagerConnection: ${{parameters.azureServiceConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/aks-main.bicep'
                csmParametersFile: '$(System.ArtifactsDirectory)/parameters/test/aks.parameters.json'
                overrideParameters: '-location $(location) -resourceGroupName $(workloadResourceGroupName) -aksSystemSubnetId $(aksSystemSubnetId) -aksUserSubnetId $(aksUserSubnetId) -azMonitorWorkspaceId $(azMonitorWorkspaceId)'
                deploymentMode: Incremental
                deploymentName: 'aks-cicd-demo-aks-deployment-test'
- stage: prod
  condition: succeededOrFailed()
  jobs:
  - deployment: 
    displayName: 'Prod AKS Deployment'
    pool:
      name: ${{parameters.poolName}}
    environment: aks-cicd-demo-prod
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'drop'
                targetPath: $(System.ArtifactsDirectory)
            - task: AzurePowerShell@5
              displayName: 'Get subscription Deployment outputs'
              inputs:
                azureSubscription: ${{parameters.azureServiceConnection}}
                azurePowerShellVersion: LatestVersion
                ScriptType: InlineScript
                pwsh: true
                Inline: |
                  $deployment = Get-AzSubscriptionDeployment -Name 'aks-cicd-demo-infra-deployment-prod'
                  Write-Host "##vso[task.setvariable variable=aksSystemSubnetId;]$($deployment.Outputs.aksSystemSubnetId.value)"
                  Write-Host "##vso[task.setvariable variable=aksUserSubnetId;]$($deployment.Outputs.aksUserSubnetId.value)"
                  Write-Host "##vso[task.setvariable variable=azMonitorWorkspaceId;]$($deployment.Outputs.azMonitorWorkspaceId.value)"
                  Write-Host "##vso[task.setvariable variable=workloadResourceGroupName;]$($deployment.Outputs.workloadResourceGroupName.value)"
                  Write-Host "##vso[task.setvariable variable=monitorResourceGroupName;]$($deployment.Outputs.monitorResourceGroupName.value)"
                  Write-Host "##vso[task.setvariable variable=networkResourceGroupName;]$($deployment.Outputs.networkResourceGroupName.value)"
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Validate Templates'
              inputs:
                deploymentScope: Subscription
                azureResourceManagerConnection: ${{parameters.azureServiceConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/aks-main.bicep'
                csmParametersFile: '$(System.ArtifactsDirectory)/parameters/prod/aks.parameters.json'
                overrideParameters: '-location $(location) -resourceGroupName $(workloadResourceGroupName) -aksSystemSubnetId $(aksSystemSubnetId) -aksUserSubnetId $(aksUserSubnetId) -azMonitorWorkspaceId $(azMonitorWorkspaceId)'
                deploymentMode: Validation
                deploymentName: 'aks-cicd-demo-aks-validation-prod'
            - task: AzureResourceManagerTemplateDeployment@3
              displayName: 'Deploy Templates'
              inputs:
                deploymentScope: Subscription
                azureResourceManagerConnection: ${{parameters.azureServiceConnection}}
                subscriptionId: ${{parameters.subscriptionId}}
                location: ${{parameters.location}}
                csmFile: '$(System.ArtifactsDirectory)/aks-main.bicep'
                csmParametersFile: '$(System.ArtifactsDirectory)/parameters/prod/aks.parameters.json'
                overrideParameters: '-location $(location) -resourceGroupName $(workloadResourceGroupName) -aksSystemSubnetId $(aksSystemSubnetId) -aksUserSubnetId $(aksUserSubnetId) -azMonitorWorkspaceId $(azMonitorWorkspaceId)'
                deploymentMode: Incremental
                deploymentName: 'aks-cicd-demo-aks-deployment-prod'