# workload-build.yaml

parameters:
  - name: vmImage
    default: 'ubuntu-latest'
    type: string
  - name: poolName
    default: 'Azure Pipelines'
    type: string

stages:
  - stage: Build
    jobs:
    - job: Build
      pool: 
        name: ${{parameters.poolName}}
        vmImage: ${{parameters.vmImage}}
      steps:
        - checkout: self
          clean: true
          persistCredentials: true
        - task: CopyFiles@2
          displayName: 'Copy Templates to Artifact Staging Directory'
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
          condition: succeeded()
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: drop'
          condition: succeeded()